SELECT 'User' as table_name, count(*) as row_count FROM "User"
UNION ALL SELECT 'PlayerIdentity', count(*) FROM "PlayerIdentity"
UNION ALL SELECT '_UserFriends', count(*) FROM "_UserFriends"
UNION ALL SELECT 'FriendRequest', count(*) FROM "FriendRequest"
UNION ALL SELECT 'Game', count(*) FROM "Game"
UNION ALL SELECT 'WizardGame', count(*) FROM "WizardGame"
UNION ALL SELECT 'TableGame', count(*) FROM "TableGame"
UNION ALL SELECT 'GameEvent', count(*) FROM "GameEvent"
UNION ALL SELECT 'GameSnapshot', count(*) FROM "GameSnapshot"
UNION ALL SELECT 'PlayerAlias', count(*) FROM "PlayerAlias"
UNION ALL SELECT 'SystemGameTemplate', count(*) FROM "SystemGameTemplate"
UNION ALL SELECT 'UserGameTemplate', count(*) FROM "UserGameTemplate"
UNION ALL SELECT 'TemplateSuggestion', count(*) FROM "TemplateSuggestion"
ORDER BY table_name;
